services:
  
  wireguard-dashboard:
    build: ./
    container_name: wg-dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    environment:
      - WGD_USER=admin
      - WGD_PASS=admin
      - WGD_NET=10.0.0.1/24
      - WGD_PORT=51820
      - WGD_APP_PORT=10086
      - WGD_REMOTE_ENDPOINT=0.0.0.0
      - WGD_DNS="1.1.1.1, 1.0.0.1"
      - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WGD_KEEP_ALIVE=21
      - WGD_MTU=1420
      - WGD_WELCOME_SESSION=false #set to true for welcome setup
    volumes:
      - wgd_configs:/etc/wireguard
      - wgd_app:/opt/wireguarddashboard/src
    ports:
      - 10086:10086/tcp 
      - 51820:51820/udp 
      # Add Port Map for New Configs and Restart Container to Apply
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
   

volumes:
    wgd_configs:
    wgd_app: