---
version: "2.1"
services:
  wireguard:
    image: aptupdate/wireguard-dashboard
    container_name: wireguard-dashboard
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      - 10086:10086/tcp
    restart: unless-stopped
