version: "3.5"

services:
  wgdashboard:
    image: donaldzou/wgdashboard
    build: 
      context: ./
      dockerfile: ./Dockerfile
    # if you want to use newer "testing" ui
    # environment:
    #   - DASHBOARD_VERSON=new
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped 
    volumes:
      - /lib/modules:/lib/modules
      - ./src:/opt/wgdashboard
      - ./config:/etc/wireguard
    ports:
      - 10086:10086
      - 51820:51820/udp